### ISSUE TITLE
"Vector length is zero"

### ISSUE THREAD

**Issue by 8824PPZ** [the3deers/android-3D-model-viewer#140]
Hello ! When I updated the latest APP from Google Store, I found that none of the 3D model files on the phone could be loaded. And they reported an error uniformly: Vector length is zero. But the old version of the APP can be loaded, it will not work after the update

**Comment by andresoviedo** [comment]
Hello.  
Please. Which models you cannot load?  the samples? What version of Android do you have?

**Comment by 8824PPZ** [comment]
> Hello.
> Please. Which models you cannot load? the samples? What version of Android do you have?

Hello!My phone is Android 9. And I can't load ".stl" files.

**Comment by 8824PPZ** [comment]
> Hello.
> Please. Which models you cannot load? the samples? What version of Android do you have?

**Comment by 8824PPZ** [comment]
Samples can be open successful, but my stl files open failed

**Comment by 8824PPZ** [comment]
Can you give me your contact information? Such as facebook contact. I am developing a 3d model recently and need your help！Thanks!

**Comment by andresoviedo** [comment]
Hello,

Please. Is it possible for you to share the model or the output of logcat?

Regards

**Comment by 8824PPZ** [comment]
Hello,how can I share the model to you ?

**Comment by andresoviedo** [comment]
Hello. Please try latest version of the app just released today.

If you still have issues, please send me your model (only for testing purposes) to my andresoviedo@gmail.com

Kind regards

**Comment by andresoviedo** [comment]
Fixed in version 3.0.3

**Comment by 8824PPZ** [comment]
Hello, I test your new version project .but  still have this question!    
`2020-09-15 16:11:56.949 12946-13082/org.andresoviedo.dddmodel2 E/MeshData: Error calculating normal. vector length is zero,[+10.2700 +6.5779 -1.3281],[+10.2700 +6.5779 -1.3264],[+10.2700 +6.5779 -1.3298]
    java.lang.IllegalArgumentException: vector length is zero
        at org.andresoviedo.util.math.Math3DUtils.normalize(Math3DUtils.java:318)
        at org.andresoviedo.android_3d_model_engine.services.collada.entities.MeshData.calculateNormalFailsafe(MeshData.java:269)
        at org.andresoviedo.android_3d_model_engine.services.collada.entities.MeshData.fixNormalsForArrays(MeshData.java:402)
        at org.andresoviedo.android_3d_model_engine.services.collada.entities.MeshData.fixNormals(MeshData.java:300)
        at org.andresoviedo.android_3d_model_engine.services.stl.STLLoaderTask.build(STLLoaderTask.java:88)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:58)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by andresoviedo** [comment]
Hello @8824PPZ 
That is an indeed a warning.  I will change that, 
In case of "Error calculating normal", a default 0,1,0 is set

Do you think that is affecting you?

Regards

**Comment by 8824PPZ** [comment]
Hello,thanks for your reply! Have you reveice my  e-mail?  This e-mail have 100MB STL Model, you can set 0,1,0 test it run normal. If the view  no  change too much , I think this is OK!  You can send me for your test result. Thanks !
